### ISSUE TITLE
请问firefox如何获取cookie？

### ISSUE THREAD

**Issue by oscarwty** [JimmyLiang-lzm/biliDownloader_GUI#11]
网络→cookie结果和chrome系格式不一样
![图片](https://user-images.githubusercontent.com/6859653/162569663-a782ac9c-0676-4e33-9f8b-284863eed336.png)

**Comment by JimmyLiang-lzm** [comment]
在消息头里面看看应该是有如Chrome的cookie样式的

**Comment by oscarwty** [comment]
> 在消息头里面看看应该是有如Chrome的cookie样式的

![图片](https://user-images.githubusercontent.com/6859653/162586905-54564f46-7863-4e35-b0fe-acbe91d09ba7.png)
那大概是这个了，我之后试试看能不能用，谢谢
