### ISSUE TITLE
某一个互动视频无法正常下载

### ISSUE THREAD

**Issue by oscarwty** [JimmyLiang-lzm/biliDownloader_GUI#12]
其他视频（包括互动视频）没有问题。
已经正确设置cookies，其他选项没动。
https://www.bilibili.com/video/BV1ca411c7b9
![图片](https://user-images.githubusercontent.com/6859653/162569826-e2face99-879e-4071-a517-e6a8e2a5e977.png)

**Comment by oscarwty** [comment]
奇怪，刚才好几次都不行，现在出来界面了，但是只能探测到序章，探测不到互动
![图片](https://user-images.githubusercontent.com/6859653/162569889-603d7001-7007-4e11-933a-70d1c2167c0b.png)

**Comment by JimmyLiang-lzm** [comment]
我这里能够访问呢，看一下网络环境怎么样呢？如果不行设置一下代理或者SSR？
![image](https://user-images.githubusercontent.com/57280094/162572698-2df8bf30-5426-4bff-a0e8-861041271b7e.png)

**Comment by oscarwty** [comment]
> 我这里能够访问呢，看一下网络环境怎么样呢？如果不行设置一下代理或者SSR？

感觉是网络的问题，我先关闭issue好了。
