### ISSUE TITLE
macOS 版添加到 homebrew 仓库

### ISSUE THREAD

**Issue by JounQin** [JimmyLiang-lzm/biliDownloader_GUI#14]

**Comment by JounQin** [comment]
<img width="184" alt="image" src="https://user-images.githubusercontent.com/8336744/168617772-34a3013e-c93f-4480-855a-6842c782de03.png">

@JimmyLiang-lzm macOS 图标有点儿问题，另外包名稍微可以优化一下？

**Comment by JounQin** [comment]
See https://github.com/Homebrew/homebrew-cask/pull/124308

**Comment by JimmyLiang-lzm** [comment]
哇塞厉害了，谢谢你能帮忙添加到homebrew仓库！！
