### ISSUE TITLE
M1 Max macOS 12.3.1 (21E258) 安装无法打开

### ISSUE THREAD

**Issue by JounQin** [JimmyLiang-lzm/biliDownloader_GUI#15]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/8336744/168467544-cc456007-1ad6-4b26-b265-a2177eac5403.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/8336744/168467587-9e76a33c-c135-4e10-973f-d90bbf4d09c4.png">

**Comment by aleass** [comment]
https://www.macwk.com/article/macos-file-damage,按照这个方法解决就好了，和软件无关是系统的安全设置而已。

**Comment by JounQin** [comment]
好吧，一般软件打开的时候会提示来自身份不明的开发者，然后安全中心会出现一个依然打开的提示按钮。
