### ISSUE TITLE
bug:FFMPEG运行出错，代码：2

### ISSUE THREAD

**Issue by aleass** [JimmyLiang-lzm/biliDownloader_GUI#17]
**你好，macos下载视频发现，合并出错，显示错误代码：FFMPEG运行出错，代码：2**
<img width="880" alt="image" src="https://user-images.githubusercontent.com/38355930/168800908-64ab89e5-e927-4b6d-9802-2704259f00ed.png">
不知道是不是这个bug：https://github.com/JimmyLiang-lzm/biliDownloader_GUI/issues/7

**系统：**
Monterry 12.3. Apple M1

**Comment by JimmyLiang-lzm** [comment]
我有时间尝试修复一下

**Comment by amirConsiderBright** [comment]
![image](https://user-images.githubusercontent.com/48363274/169316112-6ff5fbbf-330c-4009-b820-3cd8a861cded.png)
我这里是错误代码1 win10

**Comment by JimmyLiang-lzm** [comment]
这个应该是你软件的路径中有空格，这个问题我已经修复好了，准备这两天更新release

**Comment by JimmyLiang-lzm** [comment]
在**V1.6.20220521**版本以后解决错误代码：1 的问题。
