### ISSUE TITLE
下载音频出错

### ISSUE THREAD

**Issue by nicewahson** [JimmyLiang-lzm/biliDownloader_GUI#21]
https://upos-sz-mirrorbsct.bilivideo.com/upgcxcode/11/54/575735411/575735411-1-30232.m4s
下载音频出错：HTTPSConnectionPool(host='upos-sz-mirrorbsct.bilivideo.com', port=443): Max retries exceeded with url: /upgcxcode/11/54/575735411/575735411-1-30232.m4s

**Comment by JimmyLiang-lzm** [comment]
你发一下下载视频的地址，我来看看是软件的原因还是网络方面的原因
