### ISSUE TITLE
無限循環類的視頻還是打不開

### ISSUE THREAD

**Issue by WZX-Cloud1** [JimmyLiang-lzm/biliDownloader_GUI#23]

**Comment by JimmyLiang-lzm** [comment]
请说明一下具体情况，确定是否电脑挂着vpn,clash,v2ray等科学上网工具？

**Comment by WZX-Cloud1** [comment]
并没有
我打开App后按官方文档教程操作，但是一直停留在递归的界面


Jimmy Liang ***@***.***> 于2022年8月4日周四 10:21写道：

**Comment by JimmyLiang-lzm** [comment]
可以给我看一下出现问题的软件截图吗？

**Comment by WZX-Cloud1** [comment]
[image: image.png]谢谢，请帮我看一看，问题出在哪


Jimmy Liang ***@***.***> 于2022年10月8日周六 20:39写道：

**Comment by JimmyLiang-lzm** [comment]
![image](https://user-images.githubusercontent.com/57280094/195962618-88ed5c4f-afc4-46c9-b906-91fd0dd09b14.png)
我这没法看到详细的截图
