### ISSUE TITLE
Mac版本点击下载没反应

### ISSUE THREAD

**Issue by sti1l-0** [JimmyLiang-lzm/biliDownloader_GUI#3]
点击下载后，下方进度条不显示进度，只显示已就绪。下载文件夹内未出现下载文件（我不知道是否应该出现）。
鼠标悬浮在按键上方以及点击下载按钮时无反馈效果，而暂停和停止按钮有。

此外，还出现单击某些按钮会使得窗口漂移的情况。

macOS Monterey12.0.1

**Comment by JimmyLiang-lzm** [comment]
您好，请具体描述一下是在下载什么类型的视频出现的问题？

**Comment by sti1l-0** [comment]
[这个视频](https://www.bilibili.com/video/BV1ER4y1E7qn)
这个up主最近的投稿我都试过，也试过不止一种分辨率和音频码率的组合。

另，windows版本对同一地址资源探查失败。

**Comment by JimmyLiang-lzm** [comment]
**回复（2021-11-04 13:44）:**
1. 已将这个视频的地址放入版本为（V1.5.20211102-Windows10）的平台软件进行测试。经过测试：软件可以成功探查到视频资源；
2. 在（V1.5.20211102-MacOS X 10.12 Catalina）平台上进行测试，可以成功探查到视频资源；
3. 请问您使用的版本是否为最新的（V1.5.20211102）版本呢？我在考虑是不是系统不兼容或者是网络环境的问题？

**Comment by sti1l-0** [comment]
1. 在两个平台使用的都是最新版本
2. 在macOS上使用非gui版本[bilidownloader](https://github.com/JimmyLiang-lzm/biliDownloader)可以正常探查及下载
3. 测试使用的windows和macOS工作在同一网络环境中
5. 稍晚我再测试一下，感谢您的工作。

**Comment by JimmyLiang-lzm** [comment]
**回复（2021-11-04 13:44）:**
在高级设置里面可以用代理测试一下，不输入任何代理IP点击**“测试代理”**，看看下面的测试状态呢？若有条件使用一下代理IP测试一下！

**Comment by sti1l-0** [comment]
这个试过，我的代理做了路由配置，b站是不走代理的。
出现这个问题的时候，不管是否开启代理都是“测试状态：成功 地区：中国 IP”

另，macOS的深色模式会把文字变成白色，和背景一致变得无法分辨。

**Comment by JimmyLiang-lzm** [comment]
**回复（2021-11-04 22:58）:**
好的感谢你找到深色模式的适配问题！无法访问应该是因为网络环境的原因，我将继续完善。
