### ISSUE TITLE
资源探查失败

### ISSUE THREAD

**Issue by shuimutsh** [JimmyLiang-lzm/biliDownloader_GUI#30]
【【互动视频】据说99%的人，都撑不过开学第一天】 https://www.bilibili.com/video/BV19t4y177Ei?share_source=copy_web&vd_source=5db90a45e4347e4726003e24c40aef1c

**Comment by JimmyLiang-lzm** [comment]
检查是否挂梯子了，经过测试可以正常访问
![image](https://user-images.githubusercontent.com/57280094/189525389-c31bf198-bdd6-45be-a5d1-e7df1f22fcd5.png)

**Comment by nov12** [comment]
我也有一个，https://www.bilibili.com/bangumi/play/ep94082。小明和王猫，第二集就是无法下载。好奇怪。其他的都可以

**Comment by JimmyLiang-lzm** [comment]
是不是需要大会员呢？需要大会员的话就需要填写Cookie
