### ISSUE TITLE
我这边使用只能解析出480和360p

### ISSUE THREAD

**Issue by ZackRegex** [JimmyLiang-lzm/biliDownloader_GUI#33]
VIP cookie 也正常啊，是被阿B制裁了吗，为什么最高只能解析出480p的了

**Comment by ramondsq** [comment]
同样的问题，已设置 VIP Cookie

**Comment by JimmyLiang-lzm** [comment]
检查cookie是否复制正确发自我的 iPhone在 2022年11月26日，18:55，Rui Qu ***@***.***> 写道：﻿
同样的问题，已设置 VIP Cookie

**Comment by ramondsq** [comment]
> 检查cookie是否复制正确发自我的 iPhone在 2022年11月26日，18:55，Rui Qu ***@***.***> 写道：﻿ 同样的问题，已设置 VIP Cookie —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

发现问题了，我复制视频链接的时候没有复制后面的跟踪参数，就只复制到了bv号结束，只要完整复制链接地址就可以解析出所有分辨率

**Comment by ZackRegex** [comment]
大佬我知道怎么弄了
1、要复制地址栏完整链接
2、要更新VIP Cookie，现在的Cookie很容易过时失效不知道怎么回事，好像每天都得更新

**Comment by JimmyLiang-lzm** [comment]
是的，我现在在考虑用session代替cookie，这样就可以一直保存！
