### ISSUE TITLE
突然探查不到了？

### ISSUE THREAD

**Issue by JoyLin0617** [JimmyLiang-lzm/biliDownloader_GUI#37]
有添加cookie，網址也能正常拜訪，但就是探查不到資源
前幾天還可以

**Comment by senson2018** [comment]
同样问题，目前无法使用，其他小伙伴能用吗

**Comment by JimmyLiang-lzm** [comment]
昨天我测试的应该可以用，会不会是因为网络问题？

**Comment by JoyLin0617** [comment]
> 昨天我测试的应该可以用，会不会是因为网络问题？
刚刚试了下，还是不行耶
我是用这个测
https://www.bilibili.com/video/BV1GG4y1u7n8/?spm_id_from=333.788.top_right_bar_window_history.content.click

**Comment by JimmyLiang-lzm** [comment]
经过检测该视频是交互视频，但是开头是图片文件，没有音轨，所以会导致探查出现问题。
没错，你发现了BUG！！

**Comment by JimmyLiang-lzm** [comment]
现在这个BUG已经在V1.7.2版本中修复
