### ISSUE TITLE
卡巴斯基报毒

### ISSUE THREAD

**Issue by uonchou** [JimmyLiang-lzm/biliDownloader_GUI#52]
卡巴斯基报毒
![屏幕截图 2024-05-15 142849](https://github.com/JimmyLiang-lzm/biliDownloader_GUI/assets/150814969/318d35f3-67dc-44f2-8792-e1fbd8c42474)

**Comment by JimmyLiang-lzm** [comment]
如害怕release中的软件存在病毒，请阅读代码后自己搭建环境编译或运行

**Comment by JimmyLiang-lzm** [comment]
况且按照你的截图并不是程序本体报毒，报毒位置在你的Edge浏览器临时文件中
