### ISSUE TITLE
无法合并音视频文件

### ISSUE THREAD

**Issue by Leebais** [JimmyLiang-lzm/biliDownloader_GUI#7]
尊敬的开发者：

你好。我在使用你的程序是发现了bug

`self.systemd = args["sys"]`的使用在MacOS Bigsur上存在问题，debug下为`self.systemd = ""` 致使音视频合并失败.使用sys.platform应该可以会更好一些

> 建议使用如下代码在适当的位置进行替换进行替换

    import sys
    self.systemd = sys.platform

**Comment by JimmyLiang-lzm** [comment]
您好！非常感谢您提出的建议，这个建议非常的有建设性！我会在代码中改进这个问题！**再次感谢您！**😄
