### ISSUE TITLE
不知道为什么我下载下来显示该文件已损坏

### ISSUE THREAD

**Issue by zhenzhencarina** [JimmyLiang-lzm/biliDownloader_GUI#8]
如题
mac os 12.2.1 
m1

**Comment by JimmyLiang-lzm** [comment]
是存在这个问题，现在代码内已经修复了这个问题，不过还没有编译出来，周六会更新Release的

**Comment by zhenzhencarina** [comment]
喵喵喵？居然真的会有回复，期待您的作品！
晚安！
祝有美好一天！

**Comment by JimmyLiang-lzm** [comment]
最新的已经Release了，您可以下载看看！

**Comment by zhenzhencarina** [comment]
试过了好像还是不行诶？是我操作的问题嘛

**Comment by JimmyLiang-lzm** [comment]
这样你把连接发给我我试一下

**Comment by zhenzhencarina** [comment]
https://github.com/JimmyLiang-lzm/biliDownloader_GUI/releases/tag/V1.5.20220311
















在 2022-03-11 22:08:21，"Jimmy Liang" ***@***.***> 写道：

这样你把连接发给我我试一下

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JimmyLiang-lzm** [comment]
请问视频链接方便发一下么，我具体分析一下😃

**Comment by zhenzhencarina** [comment]
![127901647009243_ pic](https://user-images.githubusercontent.com/69130447/157888348-5a6cbfb5-a1a1-42d7-be42-93220cdf1ada.jpg)

**Comment by SeekingLight233** [comment]
m1  macos 11.6 可以正常打开～

**Comment by zhenzhencarina** [comment]
可能是mac自己的bug，我是12.2.1

**Comment by JimmyLiang-lzm** [comment]
您看看是不是权限的原因，看看这个链接[https://www.macapp.so/tips/mac-setup-app/](https://www.macapp.so/tips/mac-setup-app/)是否可以解决您的问题。

**Comment by zhenzhencarina** [comment]
已解决，我的安全与隐私界面没有“已组织安装这一选项”，所以我找到了通过终端解决了这个问题，感谢大佬的帮助与回复！
附上我找到的链接https://www.macwk.com/article/macos-file-damage
